### ISSUE TITLE
Adding assets in the html file

### ISSUE THREAD

**Issue by tobyl** [CKGrafico/Gulp-Boilerplates#113]
When I add an image in the HTML (JS + Sass boilerplate) the image is not found. The path I am using is `/assets/images/image-name.jpg`. This is the same path that is used in the `<head>` to link to the favicon (which does not exist).

Besides this minor issue, this project is exactly what I was looking for, thank you so much!

**note:** if I use the path `/app/assets/images/image-name.jpg` it works.

**Comment by CKGrafico** [comment]
Ooops I'm sorry for this bug, I will check the "basic" boilerplate ASAP!

**Comment by CKGrafico** [comment]
Fixed, again I'm sorry and thanks :)
