### ISSUE TITLE
Git conflict markers in code

### ISSUE THREAD

**Issue by mattgreenfield** [CKGrafico/Gulp-Boilerplates#114]
Hey, I found your repo here https://github.com/vuejs/vue-router/issues/1379#issuecomment-349600928 Thanks for your help.
There are some git merge conflict markers in your code.
https://github.com/CKGrafico/Frontend-Boilerplates/blob/e5ba032315350eb0be0233aaaf0ec04022419599/tsconfig.json#L3

**Comment by CKGrafico** [comment]
shame on me I'll check asap
